baseurl = "https://ekaschalk.github.io/"
languageCode = "en-us"
title = "Modern Emacs"
theme = "hugo-academic"
copyright = "&copy; 2017 Eric Kaschalk"

disqusShortname = "ekaschalk-github-io"
googleAnalytics = "UA-101190730-1"

enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
  name = "Eric Kaschalk"
  email = "ekaschalk@gmail.com"
  avatar = "me.jpg"

  date_format = "Mon, Jan 2, 2006"

  ##########
  # Highlighting
  ##########

  highlight = true
  highlight_languages = ["python", "lisp", "hy", "clojure"]
  highlight_style = "zenburn"

  custom_css = ["custom.css"]
  # custom_js  = []

  ##########
  # Social
  ##########

  sharing = true

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:ekaschalk@gmail.com"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/ekaschalk"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//linkedin.com/in/eric-kaschalk-782a63b7"

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[menu.main]]
  name = "My Spacemacs"
  url = "#spacemacs"
  weight = 4

[[menu.main]]
  name = "About"
  url = "#about"
  weight = 5

[taxonomies]
  tag = "tags"
  category = "categories"
